name: cubix
description: A predictable state management library that based on BLoc library. Easy to use and maintenance.
version: 0.1.4
homepage: https://github.com/linq2js/flutter_cubix
repository: https://github.com/linq2js/flutter_cubix

# must enable rps: dart pub global activate rps
scripts:
  publish: "flutter pub publish"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  hydrated_bloc:
  flutter_test:
    sdk: flutter

flutter: null
