name: cubix
description: A enhanced Bloc state management
version: 0.0.8
homepage: https://github.com/linq2js/flutter_cubix
repository: https://github.com/linq2js/flutter_cubix

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
